Created louvain communities action for community detection in networks
BenKaehler/q2-makarsa pull request #62
Opened 2023-04-04 09:27 UTC by rhernandvel

New _louvain.py script for method that allows to obtain consensus partition.
New sematic type: `Node_Community`
Updated README with python libraries needed for the Louvain method.

2023-04-05 07:09 UTC, nbokulich requested changes
thanks @rhernandvel ! I have a few comments in-line. My main comment is that unit tests are missing and needed. Transformers are also needed to make this usable with downstream actions.

I have done a somewhat high-level review more on the plugin registration and semantics... @BenKaehler could you please also test and review the functions?

2023-04-05 07:09 UTC, nbokulich commented on README.md
> +pip install netneurotools
neurotools is not conda installable (which will complicate installation). Can this be replaced by another package?

2023-04-05 07:09 UTC, nbokulich commented on q2_makarsa/_network.py
> +                raise ValidationError("")
please insert an error message here. Given that there is a separate `ParseError` I am guessing that this error would be caused by an empty table?

2023-04-05 07:09 UTC, nbokulich commented on q2_makarsa/plugin_setup.py
> +from ._network import Network, NetworkDirectoryFormat, NetworkFormat, NodeCommunityFormat, Node_Community, NodeDirectoryFormat
NodeCommunity is rather long and not too intuitive to me. What about `NodeMap` or `NetworkModules` or something like this?

2023-04-05 07:09 UTC, nbokulich commented on q2_makarsa/plugin_setup.py
> +@plugin.register_transformer
you also need a transformer to go from `NodeCommunityFormat` to `pd.DataFrame` and from `NodeCommunityFormat` to `qiime2.Metadata`. The latter will allow the `NodeCommunityFormat` artifact to be passed to other existing actions in QIIME2, e.g., for collapsing a table into modules.

2023-04-05 07:45 UTC, nbokulich commented on README.md
> +pip install netneurotools
@BenKaehler what is your input on this?

2023-04-06 21:34 UTC, BenKaehler commented
Thank you very much @rhernandvel for this commit! It is very much appreciated.

Thanks also @nbokulich for your valuable comments.

I have a few high-level comments (that are probably a bit painful, sorry).

- We have worked hard to keep the dependencies down, so I'm reluctant to add python-louvain or netneurotools.
  - Louvain community detection is available in networkx (an existing dependency). Could we use that instead?
  - Clustering consensus is a bit harder, but could we use a [VotingClassifier](https://scikit-learn.org/stable/modules/ensemble.html#voting-classifier) from scikit-learn (also an existing dependency) to similar effect?
- I agree with @nbokulich that we need to be able to use the output of this algorithm. Can we reuse an existing semantic type?
  - Probably the easiest way it to just output another network with the labels annotated on the nodes. See the spiec-easi and flashweave functions for examples of how to do that.
  - You could reuse the Hierarchy core qiime2 type. [Here](https://github.com/qiime2/q2-gneiss/blob/c24f826687627dbe3115593ebf0550b650144a27/q2_gneiss/cluster/_cluster.py#L48) is an example.

The other thing is that it will probably take me a while to take full advantage of community information. Ultimately it would be great to be able to collapse large networks interactively, but for the first release I will probably target colouring nodes. An intermediate step might be a [hierarchical edge bundling](https://vega.github.io/vega/examples/edge-bundling/) visualisation. As such, an annotated network or any output that could be transformed to metadata would work in the first instance, and we could get fancier later.

Thanks again!

2023-04-07 07:33 UTC, BenKaehler commented
After further thought, writing our own consensus clustering function would be a simple alternative to neurotools.

2023-04-14 11:40 UTC, rhernandvel commented
Thanks for the comments @BenKaehler!

- Python-louvain will be replaced by the louvain community detection in networkx. Python-louvain was initially selected because it allows to obtain a dendogram which contains all the levels in a simpler output format compared to `nx.community` `louvain_partitions`. 

- Obtaining a consensus is desirable since it has been shown to lead to more accurate partitions compared to single runs of community detection methods [(Lancichinetti & Fortunato, 2012)](https://www.nature.com/articles/srep00336).

- For the output of the algorithm, I consider that using a table format instead the of a network with the labels annotated on the nodes would be more scalable and allow for several features to be visualized in the graph. The semantic type for this would still be `NodeMap` (currently named `NodeCommunityFormat`) and the transformers to go from `NodeMap` to `pd.DataFrame` and from `NodeMap` to `qiime2.Metadata` would be included as suggested by @nbokulich .

- Taking into account that the partitions with the highest modularity per run are the ones used to generate the consensus and that a method for visualization is not available for hierarchy it would not be necessary to obtain use the Hierarchy core qiime2 type.

- Lastly, I will also check if there is a clustering algorithm in the already present libraries that could be useful and otherwise write the consensus clustering function for this.

If all this sounds good, I will proceed to integrate these steps!

2023-04-15 21:30 UTC, BenKaehler commented
Thanks @rhernandvel, that sounds great.

Will you include the full hierarchy in the node map table? You could separate levels using `"; "`, as we do for taxonomies. In fact, I would feel tempted to recycle `FeatureData[Taxonomy]` for the purpose. If you do, the visualiser will recognise the levels and allow them to be displayed without further modification. Maybe consult with @nbokulich on that one.

Regarding the consensus clustering algorithm, it looks like it would be pretty straightforward to implement. This is the one that they use in [Lancichinetti & Fortunato, 2012](https://www.nature.com/articles/srep00336):

> The starting point is a network  with n vertices and a clustering algorithm A.
>   1 Apply A on  nP times, so to yield nP partitions.
>   2 Compute the consensus matrix D, where Dij is the number of partitions in which vertices i and j of  are assigned to the same cluster, divided by nP.
>   3 All entries of D below a chosen threshold τ are set to zero.
>   4 Apply A on D nP times, so to yield nP partitions.
>   5 If the partitions are all equal, stop (the consensus matrix would be block-diagonal). Otherwise go back to 2.

I would be happy to contribute it if it comes to that.

Thanks again, I look forward to seeing your revisions.

2023-04-17 11:59 UTC, rhernandvel commented
Thanks again for the comments @BenKaehler

I was thinking of only including the level with the highest modularity in the `NodeMap` table because the consensus is obtained only for this level. If the hierarchy is to be stored, separating the levels using  `“;”` seems a suitable option.   

The consensus clustering algorithm used in [Lancichinetti & Fortunato (2012)](https://www.nature.com/articles/srep00336)  is a good option and also straightforward to implement. The downside to this method is that it generates a consensus that may correspond in some cases to a new partition different from any of the nP partions, thus losing the higher levels (hierarchy).

Looking forward to seeing your comments on this

2023-04-17 20:38 UTC, BenKaehler commented
Thanks @rhernandvel, I'm happy with you returning the level with the highest modularity. 

Does that solve the problems with the Lancichinetti & Fortunato algorithm?

Either way I'm happy with any consensus clustering algorithm you can implement or vendor.

2023-04-18 07:48 UTC, rhernandvel commented
Great! Thanks @BenKaehler 
Yes, this solves the issue with the Lancichinetti & Fortunato algorithm.
I will then include all these changes.

2023-04-28 22:30 UTC, BenKaehler commented
Hi @rhernandvel, thanks very much for your latest commit, I can't wait to try it.

Could you please tidy up a bit to remove the changes to the README and resolve the conflicts in plugin_setup.py?

I should be able to merge without conflicts and it should pass existing CI.

If you have time, some unit tests for _louvain.py would be fantastic, but we can sort that out later if you want.

Thanks!

2023-05-10 14:13 UTC, rhernandvel commented
Hi @BenKaehler ,
I removed the changes to the README and resolve the conflicts in plugin_setup.py.
I also added a test for _louvain.py.
Thanks!

2023-05-14 21:03 UTC, BenKaehler approved these changes
Thanks @rhernandvel! Very much appreciated.

2023-05-14 21:03 UTC, merged